test

diff --git a/.github/workflows/git-flow.yml b/.github/workflows/git-flow.yml
--- a/.github/workflows/git-flow.yml
+++ b/.github/workflows/git-flow.yml
@@ -25,11 +25,14 @@ jobs:
         SOURCE_BRANCH=$(jq -r ".pull_request.head.ref" "$GITHUB_EVENT_PATH")
         TARGET_BRANCH=$(jq -r ".pull_request.base.ref" "$GITHUB_EVENT_PATH")
 
+        if [[ "$SOURCE_BRANCH" == "develop" && "$TARGET_BRANCH" != "release"* ]]; then
+          echo "Error: PR from develop can only be merged to release branches."
+          #exit 1
+        fi
+
         echo $SOURCE_BRANCH
         echo $TARGET_BRANCH
 
-        echo $(.pull_request)
-        
         if [[ "$SOURCE_BRANCH" != "hotfix"* && "$SOURCE_BRANCH" != "release"* ]]; then
           echo "Error: PR can only be merged from hotfix or release branches."
           #exit 1
